In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score

input_file = "emnist-digits-train.csv"
df_train = pd.read_csv(input_file, header=None)
df_train.head()

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0    8    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    9    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    6    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    3    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    6    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 785 columns]

In [2]:
data_train = df_train.to_numpy()
data_train

array([[8, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [3]:
X_train = data_train[:, 1: ]
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Transpose

In [4]:
some_digit = X_train.reshape(240000,28,28)
transposed_digits = np.transpose(some_digit, (0, 2, 1))

X_train = transposed_digits.reshape(240000, 28 * 28)

In [5]:
y_train = data_train[:, 0]
y_train

array([8, 9, 6, ..., 1, 1, 0], dtype=int64)

In [6]:

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.neighbors import KNeighborsClassifier


extra_trees_clf = ExtraTreesClassifier(n_estimators=300, max_depth=30, random_state=42)
poly_kernel_svm_clf = SVC(kernel="poly", degree=3, coef0=1, C=100, gamma='auto', max_iter=-1, probability=True)
knn_clf = KNeighborsClassifier(n_neighbors=5, weights='distance', n_jobs=-1)
voting_clf = VotingClassifier(estimators=[('etc', extra_trees_clf), ('svc', poly_kernel_svm_clf), ('knn', knn_clf)], voting='soft')

score = cross_val_score(voting_clf, X_train, y_train, cv=10, scoring="accuracy", n_jobs=-1)

print(score)
print(np.mean(score))

# 10-CV Result
## Mean: 

In [ ]:
X_train.shape

TypeError: 'tuple' object is not callable